# Generated by Django 2.2.4 on 2021-05-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_schedule_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='codeclass',
            field=models.TextField(default=''),
        ),
    ]
