# Generated by Django 2.2.4 on 2021-05-28 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_schedule_codeclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduler', to='core.Schedule'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='description',
            field=models.CharField(blank=True, default='%H:%M:%S_%d:%m:%y', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='file',
            field=models.FileField(upload_to='input_face/detect/18Nh13/image/%H:%M:%S_%d:%m:%y'),
        ),
    ]
