# Generated by Django 2.2.4 on 2021-05-26 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default='', unique=True)),
                ('password', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeattend', models.TextField(default='')),
                ('total', models.TextField(default='')),
                ('status', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('email', models.TextField(default='')),
                ('phone', models.TextField(default='')),
                ('sex', models.BooleanField(default=True)),
                ('birthday', models.TextField(default='')),
                ('url', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='MyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(default='')),
                ('timestart', models.TextField(default='')),
                ('timeend', models.TextField(default='')),
                ('room', models.TextField(default='')),
                ('serial', models.TextField(default='')),
                ('total', models.TextField(default='')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codestudent', models.TextField(default='', unique=True)),
                ('name', models.TextField(default='')),
                ('phone', models.TextField(default='')),
                ('birthday', models.TextField(default='')),
                ('sex', models.BooleanField(default=True)),
                ('baseclass', models.TextField(default='')),
                ('status', models.IntegerField(default=0)),
                ('urlavatar', models.TextField(blank=True, default='', null=True)),
                ('urlattend', models.TextField(blank=True, default='', null=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.Attendance')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.Schedule')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Schedule'),
        ),
        migrations.AddField(
            model_name='account',
            name='infor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Info'),
        ),
    ]
