# Generated by Django 2.2.4 on 2021-05-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='file',
            field=models.FileField(upload_to='input_face/detect/18Nh13/image'),
        ),
        migrations.AlterField(
            model_name='student',
            name='codestudent',
            field=models.TextField(default=''),
        ),
    ]
