# Generated by Django 2.2.4 on 2021-05-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210526_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='code',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.TextField(default='true'),
        ),
    ]
