# Generated by Django 2.2.4 on 2021-05-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210528_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='sex',
            field=models.TextField(default='true'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.TextField(default='0'),
        ),
    ]
