# Generated by Django 2.2.4 on 2021-05-28 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210528_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='code',
        ),
    ]
